# Generated by Django 4.0.4 on 2022-06-03 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_image_talkcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkcontent',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_sent'),
        ),
    ]
